force-app/main/default/objects/MCP_Server_Config__c/MCP_Server_Config__c.object-meta.xml
<CustomObject>
    <description>This is a custom object which will store the server configuration or agent configuration for all of the agents.</description>
    <label>MCP Server Config</label>
    <nameField>
        <label>MCP Server Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCP Server Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MCP_Server_Config__c/fields/MCP_Agent_API_Name__c.field-meta.xml
<CustomField>
    <fullName>MCP_Agent_API_Name__c</fullName>
    <label>MCP_Agent_API_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MCP_Server_Config__c/fields/MCP_Downtime_Message__c.field-meta.xml
<CustomField>
    <fullName>MCP_Downtime_Message__c</fullName>
    <label>MCP_Downtime_Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MCP_Server_Config__c/fields/MCP_Status__c.field-meta.xml
<CustomField>
    <fullName>MCP_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MCP_Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MCPServerInvokeAgent.cls
public with sharing class MCPServerInvokeAgent {
    @InvocableMethod(label='Invoke Agent' description='Invokes the Agent')
    public static List<String> invokeAgent(List<InputParams> inputs) {
        List<String> outputResponse = new List<String>();
        for (InputParams input : inputs) {
            String userQuery = input.userQuery;
            String AgentResponse;
            String agentName=MCPServerConfigParse.getAgentName(userQuery);
                   agentName=agentName.Replace('"','');
            //system.debug ('Agent Name from core='+agentName);      
            //Check for agent downtime , if agent is down revert with downtime message 
            list <MCP_Server_Config__c> mcpServerConfigList = [select id ,MCP_Downtime_Message__c from MCP_Server_Config__c where MCP_Agent_API_Name__c=:agentName and MCP_Status__c=false];
            if (mcpServerConfigList.size()>0)
            {
                //Agent is down, Send the custom error message to Agent       
            //system.debug ('Final agent name'+agentName);
             AgentResponse =  mcpServerConfigList[0].MCP_Downtime_Message__c; 
             outputResponse.add(AgentResponse);
            }
            else 
            {
             Invocable.Action action =Invocable.Action.createCustomAction ('generateAiAgentResponse',agentName);
            action.setInvocationParameter('userMessage',userQuery);
            List<Invocable.Action.Result> results=action.invoke();
            Invocable.Action.Result result=results[0];
            if(result.isSuccess())
            {
                AgentResponse= (String) result.getOutputParameters().get('agentResponse');
            }
            outputResponse.add(AgentResponse);
            }
        }
        return outputResponse;
    }
    public class InputParams {
        @InvocableVariable
        public String userQuery;

    }
}